from typing import Any, Tuple, Optional, List

class UringCore:
    def __init__(
        self,
        ring_size: Optional[int] = None,
        buffer_size: Optional[int] = None,
        buffer_count: Optional[int] = None,
        try_sqpoll: Optional[bool] = None,
    ) -> None: ...
    @property
    def event_fd(self) -> int: ...
    @property
    def sqpoll_enabled(self) -> bool: ...
    @property
    def generation_id(self) -> int: ...
    def register_fd(self, fd: int, socket_type: str) -> None: ...
    def unregister_fd(self, fd: int) -> None: ...
    def pause_reading(self, fd: int) -> None: ...
    def resume_reading(self, fd: int) -> None: ...
    def check_fork(self) -> bool: ...
    def submit(self) -> int: ...
    def drain_eventfd(self) -> None: ...
    def drain_completions(self) -> list[Any]: ...
    def buffer_stats(self) -> Tuple[int, int, int, int]: ...
    def fd_stats(self) -> Tuple[int, int, int, int]: ...
    def signal(self) -> None: ...
    def submit_recv(self, fd: int) -> None: ...
    def submit_send(self, fd: int, data: bytes) -> None: ...
    def submit_accept(self, fd: int) -> None: ...
    def submit_close(self, fd: int) -> None: ...
    def shutdown(self) -> None: ...
    def push_timer(self, expiration: float, handle: Any) -> None: ...
    def pop_expired(self, now: float) -> list[Any]: ...
    def next_expiration(self) -> Optional[float]: ...

__version__: str
__author__: str
